#! /bin/bash -

# ENVIRONMENT VARIABLES

JDK_PATH=../../apps/jdk1.5.0_05
COMMONS_CLI=./lib/commons-cli-1.0.jar
WEKA=../../apps/weka-3-4/weka.jar

# ---------------------

LIBS=.:$WEKA:$COMMONS_CLI:bin/

rm bin/recognizer/*.class;

$JDK_PATH/bin/javac  -classpath $LIBS src/recognizer/PersonalityRecognizer.java src/recognizer/Utils.java -d bin/



